---
# tasks file for smsearcy.bitbucket

- name: create user
  user:
    name: "{{ bitbucket_user }}"
    password: "*"
    home: "{{ bitbucket_home }}"
    uid: "{{ bitbucket_uid | default(omit) }}"
    shell: "/bin/bash"
  notify: restart bitbucket
  tags: smsearcy.bitbucket

- name: unarchive package
  unarchive:
    copy: no
    src: "{{ bitbucket_url }}"
    dest: "{{ bitbucket_install }}"
    creates: "{{ bitbucket_catalina }}/bin/setenv.bat"
  notify: restart bitbucket
  tags: smsearcy.bitbucket

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "bitbucket.service.j2", dest: "/etc/systemd/system/bitbucket.service", owner: "root", group: "root", mode: "0644" }
    - { src: "setenv.sh.j2", dest: "{{ bitbucket_catalina }}/bin/setenv.sh", owner: "root", group: "root", mode: "0644" }
    - { src: "server.xml.j2", dest: "{{ bitbucket_home }}/shared/server.xml", owner: "{{ bitbucket_user }}", group: "{{ bitbucket_user }}", mode: "0644" }
  notify: restart bitbucket
  tags: smsearcy.bitbucket

- name: enable service
  service:
    name: "bitbucket"
    enabled: "yes"
  notify: restart bitbucket
  tags: smsearcy.bitbucket
