# -*- mode: ruby -*-
# vi: set ft=ruby :

# Based on https://github.com/geerlingguy/ansible-vagrant-examples/blob/master/jenkins/Vagrantfile

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.2"
  #config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.name = "bitbucket"
    v.memory = 1024
    v.cpus = 2
    #v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    #v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.hostname = "bitbucket"
  config.vm.network "private_network", ip: "192.168.33.10"

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :bitbucket do |bitbucket|
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.sudo = true
    ansible.verbose = "vvvv"
  end

end
